### ISSUE TITLE
Super Focus mode does not show other obsidian windows

### ISSUE THREAD

**Issue by Archie-2021** [ryanpcmcquen/obsidian-focus-mode#47] opened 2023-01-17 08:06 UTC
I just noticed that when I activate super focus mode, the other obsidian window I have on the other monitor goes black. Can you change that?

Thanks

**Comment by ryanpcmcquen** [comment] 2023-01-17 08:07
Does that also happen in normal Focus Mode?

**Comment by Archie-2021** [comment] 2023-01-17 08:16
> Does that also happen in normal Focus Mode?

No it doesn't for me.

**Comment by ryanpcmcquen** [comment] 2023-01-17 08:17
This sounds like intended functionality. Super Focus Mode should black out everything except the main pane.

**Comment by Archie-2021** [comment] 2023-01-17 08:21
> This sounds like intended functionality. Super Focus Mode should black out everything except the main, active pane.

Well , doing it for everything made sense when there was not window function in obsidian, but now different windows could be in different workspaces even. They are going to be totally unrelated.

**Comment by ryanpcmcquen** [comment] 2023-01-17 08:23
So this is happening for windows in different 'workspaces'? I'm not even familiar with the 'workspace' functionality in Obsidian.

**Comment by Archie-2021** [comment] 2023-01-17 08:33
> 



> So this is happening for windows in different 'workspaces'? I'm not even familiar with the 'workspace' functionality in Obsidian.

Not obsidian workspace, I am talking about Desktop Environment workspace, like having a set of notes related to project A open in workspace 1 and another set of notes in different window for project B. If I focus on one note in project A I would not be able to see anything in notes for project B.

**Comment by ryanpcmcquen** [comment] 2023-01-17 08:34
Are they separate vaults?

**Comment by Archie-2021** [comment] 2023-01-17 08:35
No, same vault(I don't think for different vaults this be an issue).

**Comment by ryanpcmcquen** [comment] 2023-01-17 08:36
And does Obsidian have awareness of your desktop environment workspaces? If not, I'm not sure how this would be solved.

**Comment by ryanpcmcquen** [comment] 2023-01-17 08:45
Even if this were solvable, I don't have a multi monitor setup to reproduce it with, and it seems that this request is seeking functionality from Super Focus Mode that should be left to normal Focus Mode.

**Comment by Archie-2021** [comment] 2023-01-17 09:14
> Even if this were solvable, I don't have a multi-monitor setup to reproduce it with, and it seems that this request is seeking functionality from Super Focus Mode that should be left to normal Focus Mode.



> Even if this were solvable, I don't have a multi-monitor setup to reproduce it with, and it seems that this request is seeking functionality from Super Focus Mode that should be left to normal Focus Mode.

I doesn't need a multi-monitor setup, just open two obsidian windows side by side and see. If you have two panes open in a window, there is a huge difference between normal focus mode and super focus, super focus basically maximizes the current tab to take all the windows space temporarily, which is super useful. All older plugins which had this feature that I knew broke in one of the previous updates (and not fixed last I check while ago. 

I just thought it is a good idea to report this issue, that is all.
Thanks

**Comment by ryanpcmcquen** [comment] 2023-01-17 16:37
The idea of Super Focus Mode is to focus on one thing, and one thing only. Having separate windows that you are working on implies by default that one would be focusing on multiple things.

Still, this should be solvable with a CSS snippet.

**Comment by Steven-AA** [comment] 2023-02-12 05:59
I usually open two pane left right split. I use super focus mode to full screen one note. So I prefer my other obsidian window in another monitor still working. Or maybe there is another way to full screen one note without closing other panes?

**Comment by Steven-AA** [comment] 2023-02-12 06:03
found https://github.com/razumihin/obsidian-fullscreen-plugin

**Comment by Archie-2021** [comment] 2023-02-21 17:11
> found https://github.com/razumihin/obsidian-fullscreen-plugin

I don't think it is uptodate tho. There were many plugins with fullscreen feature but most of them broke after  some major obsidian update. I would love to know if any of them work.

**Comment by Steven-AA** [comment] 2023-02-22 02:28
> > found https://github.com/razumihin/obsidian-fullscreen-plugin
> 
> I don't think it is uptodate tho. There were many plugins with fullscreen feature but most of them broke after some major obsidian update. I would love to know if any of them work.

This is an amazingly simple plugin with only one feature, full screen. Last update one year ago, but I have been using it for a week, it works great.

**Comment by Steven-AA** [comment] 2023-02-22 02:28
> > found https://github.com/razumihin/obsidian-fullscreen-plugin
> 
> I don't think it is uptodate tho. There were many plugins with fullscreen feature but most of them broke after some major obsidian update. I would love to know if any of them work.

This is an amazingly simple plugin with only one feature, full screen. Last update one year ago, but I have been using it for a week, it works great.

**Closed** 2023-03-15 17:12 UTC
