### ISSUE TITLE
Disappearing inline title.

### ISSUE THREAD

**Issue by martincodez** [ryanpcmcquen/obsidian-focus-mode#51] opened 2023-10-04 07:51 UTC
I love this plugin and it is key to my workflow. 

I think I have found a bug that happens when you focus in on a pane, the inline title (not the tab title) disappears. A restart of Obsidian is needed in order to bring the inline, top of the note, title back.

This happens on the latest obsidian using the minimal theme.

Can we fix this?

Thank you for all the work you do.

**Comment by brandonkboswell** [comment] 2023-10-13 22:48
@martincodez I don't think this is a bug, it's just a feature that's not configurable. I find if I toggle off focus mode (not Super Focus) then the title comes back. With that said, I personally would find it helpful if this was configurable as I love Super Focus mode, but would still like to be able to maintain my Inline Title.

**Comment by ryanpcmcquen** [comment] 2023-12-14 20:47
Duplicate of:
https://github.com/ryanpcmcquen/obsidian-focus-mode/issues/45
This is already possible with a CSS snippet.

**Closed by ryanpcmcquen** 2023-12-14 20:47 UTC
