### ISSUE TITLE
Fix issues with California Coast theme?

### ISSUE THREAD

**Issue by ryanpcmcquen** [ryanpcmcquen/obsidian-focus-mode#8] opened 2021-05-21 17:39 UTC
@AidenLx reported some issues with the California Coast theme. I merged that PR:
https://github.com/ryanpcmcquen/obsidian-focus-mode/pull/6

But it caused some other issues (the default theme was not displaying correctly, and the command palette would not show in Focus Mode).

If possible, we should add some changes that would fix the California Coast issues without introducing other issues.

**Comment by ryanpcmcquen** [comment] 2021-05-21 18:43
@AidenLx if you have time, please try some other methods here.

**Comment by AidenLx** [comment] 2021-05-22 00:35
I could not reproduce the problem of the command palette not showing up. Which commit are you using for testing? if you revert my changes, it's hard for me to debug.

**Comment by ryanpcmcquen** [comment] 2021-05-22 00:37
There have been a lot of changes after I reverted those. Does the latest release still have issues with the California Coast theme? Are you testing with the default Light theme?

**Comment by AidenLx** [comment] 2021-05-22 00:45
I've tested the latest release and nothing is fixed, and I've fixed a problem in [here](https://github.com/alx-plugins/obsidian-focus-mode/commit/4230ef46ad60d654c3077453ecd94d93c6a507cf). Also, maybe consider a separate commit with `git revert` command? It could be much better than a manual revert.

**Comment by AidenLx** [comment] 2021-05-22 00:54
![image](https://user-images.githubusercontent.com/31102694/119209655-6bd9ba00-bada-11eb-8fbf-17e1514b130c.png)
the gray bar at the bottom is fixed in [4230ef](https://github.com/alx-plugins/obsidian-focus-mode/commit/4230ef46ad60d654c3077453ecd94d93c6a507cf), 
and the right ribbon is fixed in [82fed3](https://github.com/alx-plugins/obsidian-focus-mode/commit/82fed3415b1802cf09f69230a31e92ba42cdfb6b)

**Comment by ryanpcmcquen** [comment] 2021-05-22 01:00
Yeah, reverts are great but would have created a bunch of merge conflicts in this case. I will give another try with your changes, but I don't use the mentioned theme.

**Comment by AidenLx** [comment] 2021-05-22 01:11
I've opened a pull request. you can clone it from my repo and try it first before you merge it into yours.

**Closed** 2021-05-22 20:15 UTC
Labels: enhancement, help wanted
