### ISSUE TITLE
Failed to load plugin - there is no main.js in this repository?

### ISSUE THREAD

**Issue by twirley** [ryanpcmcquen/obsidian-focus-mode#52] opened 2023-12-04 08:04 UTC
Hi,

### I can't activate this plugin.
It appears in Obsidian
![image](https://github.com/ryanpcmcquen/obsidian-focus-mode/assets/71321660/5b2a9238-cbc7-4221-94c6-4d06f7d9a608)
But I can't activate it.

#### Activating gives me this error
![image](https://github.com/ryanpcmcquen/obsidian-focus-mode/assets/71321660/d86ee73d-6f51-4054-b2a8-f1b33ddae85b)

**I tried some fixes I found**, like deleting 
app.json the folder above, restarting and so forth. Nothing worked so far.
I also tried renaming  main.ts to main.js, because...

#### I'm not sure, if this is relvant?
Your guide said
![image](https://github.com/ryanpcmcquen/obsidian-focus-mode/assets/71321660/4115e843-9718-4e4c-b816-d2a3e8c8d73d)

But there is no such named file in this repository. There is only
![image](https://github.com/ryanpcmcquen/obsidian-focus-mode/assets/71321660/702844e1-ddd9-4610-8a03-3cb49dfba825)

Do you have any guesses, what might be causing this or what I could try?

**Comment by ryanpcmcquen** [comment] 2023-12-14 20:46
Did Obsidian change the requirements for loading plugins?

**Comment by ryanpcmcquen** [comment] 2023-12-14 20:50
@twirley, what was your install method? Did you use files from the release or use Obsidian's community plugins store?

**Comment by ryanpcmcquen** [comment] 2024-06-15 14:25
Closing as I am unable to reproduce.

**Closed by ryanpcmcquen** 2024-06-15 14:25 UTC
