### ISSUE TITLE
Toggle super focus mode not exiting

### ISSUE THREAD

**Issue by maxwellhibbert** [ryanpcmcquen/obsidian-focus-mode#44] opened 2022-11-26 00:20 UTC
Hi, I just setup your plugin to use the super focus mode and the toggle doesn't seem to work to exit the mode.

**Comment by ryanpcmcquen** [comment] 2022-11-26 02:51
Duplicate of:
https://github.com/ryanpcmcquen/obsidian-focus-mode/issues/42

**Closed by ryanpcmcquen** 2022-11-26 02:51 UTC
